---
title: "Cleaning soil isotopes data"
author: "Camila Vargas"
date: "10/8/2021"
output: html_document
---

## Set up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(readxl)
library(janitor)
library(lubridate)

## Sets R not to use scientific notations
options(scipen=999) 

```


## Check all necesary files are in the raw_data folder

```{r}
## File path to raw data used in this script
raw_data_path <- here::here("raw_data")

# Count files inside the raw_data folder to make sure the number of files downloaded is what is expected.
length(list.files(raw_data_path, pattern = "soil"))

## in this case there should be **4** files
```


## Table with all the raw data files
```{r}

## List with all xls files
all_xls <- tibble(list.files(raw_data_path, pattern = "soil")) %>% #c("xls", "xlsx")
  rename(file_name = 1) %>% 
  mutate(path = paste0(raw_data_path, "/", file_name),
         n = 1:n(),
         ### UPDATE
         type = "soil") %>% 
  unite(obj_name, type, n, sep = "_", remove = FALSE)

```


## Read data


```{r}
## check sheet names
excel_sheets(all_xls$path[1]) ## Only sheet one has data

soil_07_08 <- read_excel(all_xls$path[1], sheet = "Sheet1") %>% 
  clean_names()

```



